import {bootShell} from './shell.js';
import {supabase,esc} from './supabase.js';
import {showConfirm,showPromptDialog} from './confirmDialog.js';
import {ATTENDANCE_TYPES,calendarDays,summarizeDays,validatePeriod} from './attendanceModel.js';
let profile,period=null,employees=[],busy=false;
const $=id=>document.getElementById(id),error=e=>{$('sheetError').textContent=e.message||e;$('sheetError').classList.add('show');};
const rows=()=>[...document.querySelectorAll('#sheetRows tr')].map(tr=>({date:tr.dataset.date,status:tr.querySelector('select').value,units:Number(tr.querySelector('input[type=number]').value),note:tr.querySelector('input[type=text]').value}));
function totals(){try{const s=summarizeDays(rows());$('sheetTotals').textContent=`Công hưởng lương: ${s.paid} · Không lương: ${s.unpaid} · Vắng: ${s.absent} · Chưa nhập: ${s.missing}`;}catch(e){error(e);}}
function controls(){const editable=profile.departmentCode==='HR'&&(!period||period.status==='draft');for(const id of ['saveSheet','submitSheet'])$(id).hidden=!editable;for(const id of ['returnSheet','lockSheet'])$(id).hidden=profile.departmentCode!=='ACC'||period?.status!=='submitted';document.querySelectorAll('#sheetRows input,#sheetRows select,#standardDays').forEach(el=>el.disabled=!editable);$('sheetStatus').textContent=({draft:'Nháp',submitted:'Chờ kế toán',locked:'Đã chốt'})[period?.status]||'Chưa lập';}
async function load(){if(busy)return;$('sheetError').classList.remove('show');const [y,m]=$('periodMonth').value.split('-').map(Number),empId=$('employeeSelect').value;if(!empId)return;
const {data,error:e}=await supabase.from('attendance_periods').select('*').eq('employee_id',empId).eq('year',y).eq('month',m).maybeSingle();if(e)throw e;period=data;$('standardDays').value=period?.standard_days||26;const {data:days,error:dayError}=period?await supabase.from('attendance_days').select('*').eq('period_id',period.id):{data:[]};if(dayError)throw dayError;const map=new Map((days||[]).map(d=>[d.work_date,d]));
$('sheetTitle').textContent=employees.find(e=>e.id===empId)?.full_name||'Bảng công';$('sheetRows').innerHTML=calendarDays(y,m).map(date=>{const d=map.get(date)||{};return `<tr data-date="${date}"><td>${date.slice(8)}/${date.slice(5,7)}</td><td><select aria-label="Loại công ${date}" class="select-input"><option value="">Chưa nhập</option>${Object.entries(ATTENDANCE_TYPES).map(([k,v])=>`<option value="${k}" ${d.status===k?'selected':''}>${v}</option>`).join('')}</select></td><td><input type="number" min="0" max="1" step="0.5" class="text-input" aria-label="Số công ${date}" value="${d.units??1}"></td><td><input type="text" class="text-input" aria-label="Ghi chú ${date}" value="${esc(d.note||'')}"></td></tr>`;}).join('');$('sheetRows').onchange=e=>{if(e.target.tagName==='SELECT'){const input=e.target.closest('tr').querySelector('input[type=number]');input.value=e.target.value==='off'?0:1;}totals();};controls();totals();
if(period){const {data:audit}=await supabase.from('attendance_audit').select('action,created_at,after_data').eq('period_id',period.id).order('created_at',{ascending:false}).limit(20);$('sheetAudit').innerHTML=(audit||[]).map(a=>`<p>${esc(a.action)} · ${new Date(a.created_at).toLocaleString('vi-VN')} ${esc(a.after_data?.note||'')}</p>`).join('')||'Chưa có lịch sử.';}else $('sheetAudit').textContent='Chưa có lịch sử.';
}
async function act(fn){if(busy)return;busy=true;document.querySelectorAll('.modal-actions button').forEach(b=>b.disabled=true);try{await fn();}catch(e){error(e);}finally{busy=false;document.querySelectorAll('.modal-actions button').forEach(b=>b.disabled=false);await load().catch(error);}}
async function save(){const [y,m]=$('periodMonth').value.split('-').map(Number);const days=rows().filter(d=>d.status);const {error:e}=await supabase.rpc('save_attendance_period',{p_employee_id:$('employeeSelect').value,p_year:y,p_month:m,p_standard_days:Number($('standardDays').value),p_days:days,p_expected_version:period?.version||0});if(e)throw e;}
$('saveSheet').onclick=()=>act(save);$('submitSheet').onclick=async()=>{try{validatePeriod(rows(),Number($('standardDays').value));if(!await showConfirm('Gửi bảng công này cho kế toán? Sau khi gửi, HCNS cần được trả lại để sửa.'))return;await act(async()=>{await save();const [y,m]=$('periodMonth').value.split('-').map(Number);const {data:p,error:e}=await supabase.from('attendance_periods').select('id,version').eq('employee_id',$('employeeSelect').value).eq('year',y).eq('month',m).single();if(e)throw e;const {error:t}=await supabase.rpc('transition_attendance_period',{p_id:p.id,p_action:'submit',p_expected_version:p.version,p_note:''});if(t)throw t;});}catch(e){error(e);}};
$('lockSheet').onclick=async()=>{if(await showConfirm('Chốt bảng công? Kế toán sẽ tính lương theo số công này.'))act(async()=>{const {error:e}=await supabase.rpc('transition_attendance_period',{p_id:period.id,p_action:'lock',p_expected_version:period.version,p_note:''});if(e)throw e;});};
$('returnSheet').onclick=async()=>{const note=await showPromptDialog('Lý do trả bảng công cho HCNS:',{required:true});if(note===null)return;act(async()=>{const {error:e}=await supabase.rpc('transition_attendance_period',{p_id:period.id,p_action:'return',p_expected_version:period.version,p_note:note});if(e)throw e;});};
$('exportSheet').onclick=()=>{const quote=v=>'"'+String(v).replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"';const text='\ufeffNgày,Loại công,Số công,Ghi chú\r\n'+rows().map(d=>[d.date,ATTENDANCE_TYPES[d.status]||'Chưa nhập',d.units,d.note].map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='bang-cong.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
for(const id of ['periodMonth','employeeSelect','refreshSheet'])$(id).addEventListener(id==='refreshSheet'?'click':'change',()=>load().catch(error));
(async()=>{({profile}=await bootShell());const now=new Date();$('periodMonth').value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;let q=supabase.from('employees').select('id,full_name,employee_code').eq('status','active').order('full_name');if(!['HR','ACC'].includes(profile.departmentCode)&&!['EXECUTIVE','TECH'].includes(profile.roleCode))q=q.eq('id',profile.id);const {data,error:e}=await q;if(e)throw e;employees=data||[];$('employeeSelect').innerHTML=employees.map(e=>`<option value="${e.id}">${esc(e.full_name)} · ${esc(e.employee_code||'')}</option>`).join('');await load();})().catch(error);
