import {bootShell} from './shell.js';import {zodiacFor,nextPlayer,randomStar} from './breakRoomModel.js';
const $=id=>document.getElementById(id);let key='ais-game-best',best=0,player={x:7,y:5},star=randomStar(player),points=0,remaining=60,running=false,lastTime=0,timer=null;
const canvas=$('starCanvas'),ctx=canvas.getContext('2d');
function draw(){ctx.fillStyle='#f1efe8';ctx.fillRect(0,0,480,320);ctx.strokeStyle='#e3e0d5';for(let x=0;x<15;x++)for(let y=0;y<10;y++){ctx.strokeRect(x*32,y*32,32,32);}ctx.fillStyle='#233b57';ctx.fillRect(player.x*32+4,player.y*32+4,24,24);ctx.fillStyle='#ae894b';ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?6:13,x=star.x*32+16+Math.cos(a)*r,y=star.y*32+16+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();}
function move(direction){if(!running)return;player=nextPlayer(player,direction);if(player.x===star.x&&player.y===star.y){points+=10;star=randomStar(player);$('gameScore').textContent='Điểm: '+points;}draw();}
function stop(message){running=false;clearInterval(timer);timer=null;$('pauseGame').textContent='Tiếp tục';$('gameMessage').textContent=message;}
function tick(){const now=performance.now();remaining=Math.max(0,remaining-(now-lastTime)/1000);lastTime=now;$('gameClock').textContent=Math.ceil(remaining)+' giây';if(remaining===0){stop(`Hoàn tất! Bạn thu được ${points} điểm.`);$('pauseGame').disabled=true;if(points>best){best=points;try{localStorage.setItem(key,String(best));}catch{}$('gameBest').textContent='Kỷ lục: '+best;}}}
function resume(){if(remaining<=0)return;running=true;lastTime=performance.now();timer=setInterval(tick,250);$('pauseGame').textContent='Tạm dừng';$('gameMessage').textContent='Chạm ngôi sao để ghi điểm.';}
$('startGame').onclick=()=>{clearInterval(timer);player={x:7,y:5};star=randomStar(player);points=0;remaining=60;$('gameScore').textContent='Điểm: 0';$('gameClock').textContent='60 giây';$('pauseGame').disabled=false;resume();draw();canvas.focus();};$('pauseGame').onclick=()=>running?stop('Đã tạm dừng.'):resume();document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>move(b.dataset.move));canvas.addEventListener('keydown',e=>{const d={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'}[e.key];if(d){e.preventDefault();move(d);}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)stop('Đã tạm dừng khi bạn rời tab.');});window.addEventListener('pagehide',()=>clearInterval(timer));draw();
$('readZodiac').onclick=()=>{const value=$('zodiacBirthday').value,date=new Date(value+'T00:00:00Z');if(!value||Number.isNaN(date.getTime())||date>Date.now()){$('zodiacResult').textContent='Vui lòng nhập ngày sinh hợp lệ.';return;}const sign=zodiacFor(date),messages=['Hôm nay, hãy chọn một việc quan trọng và hoàn thành thật chỉn chu.','Một cuộc trò chuyện rõ ràng có thể giúp công việc nhẹ nhàng hơn.','Dành vài phút sắp xếp lại kế hoạch; sự bình tĩnh là lợi thế của bạn.','Một lời cảm ơn nhỏ có thể làm ngày làm việc của cả nhóm tốt hơn.','Bạn không cần làm mọi việc cùng lúc. Một bước vững vàng đã là tiến bộ.'];const day=new Date(),index=(date.getUTCDate()+date.getUTCMonth()+day.getDate())%messages.length;$('zodiacResult').textContent=`${sign} — ${messages[index]}`;};
bootShell().then(({profile})=>{key='ais-game-best:'+profile.id;try{best=Math.max(0,Math.min(100000,Number(localStorage.getItem(key))||0));}catch{}$('gameBest').textContent='Kỷ lục: '+best;}).catch(e=>console.error(e));
