import {bootShell} from './shell.js';import {supabase,esc,resolveFileUrl,uploadPrivateFile} from './supabase.js';import {showConfirm,showPromptDialog} from './confirmDialog.js';import {DOCUMENT_TEMPLATES,validateDocument} from './documentTemplates.js';import {buildDocumentPdf,downloadPdf,hashPdf,SIGN_ROLES} from './documentPdf.js';
let profile,people=[],documents=[],busy=false,previewUrl=null,previewVersion=0,previewTimer,signaturePath=null;
const $=id=>document.getElementById(id),err=e=>{$('documentError').textContent=e.message||e;$('documentError').classList.add('show');};
const template=()=>DOCUMENT_TEMPLATES.find(t=>t.code===$('documentType').value);
const payload=()=>Object.fromEntries(template().fields.map(f=>[f.key,$(f.key).value]));
const signer=(d,step=d.current_step)=>[d.creator_id,d.manager_id,d.hr_id,d.director_id][step];
function fields(d,t){return t.fields.map(f=>({label:f.label,value:d.payload[f.key]||'—'}));}
function render(){const q=$('documentSearch').value.toLowerCase(),filter=$('documentFilter').value;const data=documents.filter(d=>(d.code+' '+(DOCUMENT_TEMPLATES.find(t=>t.code===d.template_code)?.title||d.template_code)).toLowerCase().includes(q)&&(filter==='all'||filter==='mine'&&d.creator_id===profile.id||filter==='pending'&&d.status==='signing'&&signer(d)===profile.id||d.status===filter));$('documentList').innerHTML=data.map(d=>`<article class="document-card"><div><p class="workspace-kicker">${esc(d.code)}</p><h3>${esc(DOCUMENT_TEMPLATES.find(t=>t.code===d.template_code)?.title||d.template_code)}</h3><p>${d.status==='approved'?'Đã ký đủ 4 cấp':d.status==='rejected'?`Từ chối: ${esc(d.reject_reason)}`:`Chờ ${SIGN_ROLES[d.current_step]} ký`}</p><small>${new Date(d.created_at).toLocaleDateString('vi-VN')}</small></div><ol class="document-steps">${SIGN_ROLES.map((r,i)=>`<li class="${i<d.current_step?'done':i===d.current_step?'current':''}">${i<d.current_step?'✓':i+1} ${r}</li>`).join('')}</ol><div class="document-actions"><button class="btn btn-outline" data-pdf="${d.id}">Xuất PDF</button>${d.status==='signing'&&signer(d)===profile.id?`<button class="btn btn-accent" data-sign="${d.id}">Ký ${SIGN_ROLES[d.current_step]}</button>${d.current_step>0?`<button class="btn btn-outline" data-reject="${d.id}">Từ chối</button>`:''}`:''}</div></article>`).join('')||'<div class="workspace-empty">Chưa có hồ sơ phù hợp.</div>';
 document.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>action(()=>exportDocument(documents.find(d=>d.id===b.dataset.pdf))));document.querySelectorAll('[data-sign]').forEach(b=>b.onclick=()=>action(()=>signDocument(documents.find(d=>d.id===b.dataset.sign))));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>action(async()=>{const d=documents.find(d=>d.id===b.dataset.reject),reason=await showPromptDialog('Lý do từ chối:',{required:true});if(reason===null)return;const {error}=await supabase.rpc('reject_employee_document',{p_id:d.id,p_expected_version:d.version,p_reason:reason});if(error)throw error;}));}
async function load(more=false){const offset=more?documents.length:0;const {data,error}=await supabase.from('employee_documents').select('*').order('created_at',{ascending:false}).range(offset,offset+99);if(error)throw error;documents=more?[...documents,...(data||[])]:data||[];$('moreDocuments').hidden=(data||[]).length<100;render();}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('#documentList button,#createDocument').forEach(b=>b.disabled=true);$('documentError').classList.remove('show');try{await fn();}catch(e){err(e);}finally{busy=false;$('createDocument').disabled=false;await load().catch(err);}}
async function signatures(d){const {data,error}=await supabase.from('employee_document_signatures').select('*').eq('document_id',d.id).order('step');if(error)throw error;return Promise.all((data||[]).map(async s=>{const response=await fetch(await resolveFileUrl(s.signature_path,900));if(!response.ok)throw new Error('Không tải được chữ ký đã lưu.');return {step:s.step,name:s.signer_name,at:s.signed_at,image:await response.blob()};}));}
async function exportDocument(d){if(d.pdf_path){const response=await fetch(await resolveFileUrl(d.pdf_path,900));if(!response.ok)throw new Error('Không tải được PDF.');downloadPdf(await response.blob(),d.code+'.pdf');}else{const t=DOCUMENT_TEMPLATES.find(t=>t.code===d.template_code);downloadPdf(await buildDocumentPdf({title:t.title,code:d.code,author:people.find(p=>p.id===d.creator_id)?.full_name||profile.fullName,fields:fields(d,t)}),d.code+'.pdf');}}
async function signDocument(d){if(!signaturePath)throw new Error('Bạn chưa cập nhật chữ ký. Mở Hồ sơ cá nhân để tải ảnh chữ ký PNG/JPG.');if(!await showConfirm(`Ký xác nhận hồ sơ ${d.code}? Nội dung đã khóa và chữ ký sẽ được lưu vào lịch sử.`))return;
 const t=DOCUMENT_TEMPLATES.find(t=>t.code===d.template_code),signed=await signatures(d),response=await fetch(await resolveFileUrl(signaturePath,900));if(!response.ok)throw new Error('Không tải được chữ ký cá nhân.');const signatureBlob=await response.blob();const signatureSnapshot=`employee-documents/${d.id}/signatures/${d.current_step}-${crypto.randomUUID()}.${signatureBlob.type.includes('png')?'png':'jpg'}`;await uploadPrivateFile(signatureSnapshot,signatureBlob,{contentType:signatureBlob.type});signed.push({step:d.current_step,name:profile.fullName,at:new Date().toISOString(),image:signatureBlob});const blob=await buildDocumentPdf({title:t.title,code:d.code,author:people.find(p=>p.id===d.creator_id)?.full_name||'',fields:fields(d,t),signatures:signed});const path=`employee-documents/${d.id}/${d.current_step}-${crypto.randomUUID()}.pdf`;await uploadPrivateFile(path,blob,{contentType:'application/pdf'});const {error}=await supabase.rpc('sign_employee_document',{p_id:d.id,p_step:d.current_step,p_expected_version:d.version,p_pdf_path:path,p_sha256:await hashPdf(blob),p_signature_path:signatureSnapshot});if(error)throw error;}
function populate(){const t=template();$('documentFields').innerHTML=t.fields.map(f=>`<div class="field"><label for="${f.key}">${esc(f.label)}${f.required?' *':''}</label>${f.type==='textarea'?`<textarea id="${f.key}" rows="3" ${f.required?'required':''}></textarea>`:`<input id="${f.key}" type="${f.type}" ${f.required?'required':''} ${f.type==='number'?'min="0" step="0.5"':''}>`}</div>`).join('');schedulePreview();}
function schedulePreview(){clearTimeout(previewTimer);previewVersion++;const token=previewVersion;previewTimer=setTimeout(async()=>{try{$('previewStatus').textContent='Đang tạo PDF…';const t=template(),data=payload(),blob=await buildDocumentPdf({title:t.title,author:profile.fullName,fields:t.fields.map(f=>({label:f.label,value:data[f.key]}))});if(token!==previewVersion)return;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);$('documentPreview').src=previewUrl;$('previewStatus').textContent='PDF có 4 vị trí ký; nội dung cập nhật từ thông tin đã điền.';}catch(e){$('previewStatus').textContent=e.message;}},650);}
$('documentForm').addEventListener('input',schedulePreview);$('documentType').onchange=populate;$('newDocument').onclick=()=>{$('documentCreate').hidden=false;populate();$('documentCreate').scrollIntoView({behavior:'smooth'});};$('cancelDocument').onclick=()=>{$('documentCreate').hidden=true;};$('documentSearch').oninput=render;$('documentFilter').onchange=render;$('refreshDocuments').onclick=()=>load().catch(err);$('moreDocuments').onclick=()=>load(true).catch(err);
$('documentForm').onsubmit=e=>{e.preventDefault();action(async()=>{if(!signaturePath)throw new Error('Vui lòng cập nhật chữ ký cá nhân trước khi tạo hồ sơ.');const t=template(),data=validateDocument(t,payload());const ids=[profile.id,$('managerSigner').value,$('hrSigner').value,$('directorSigner').value];if(ids.some(v=>!v)||new Set(ids).size!==4)throw new Error('Cần chọn 4 người ký khác nhau.');const {data:id,error}=await supabase.rpc('create_employee_document',{p_type:t.code,p_data:data,p_manager:ids[1],p_hr:ids[2],p_director:ids[3]});if(error)throw error;const {data:d,error:e}=await supabase.from('employee_documents').select('*').eq('id',id).single();if(e)throw e;$('documentCreate').hidden=true;await signDocument(d);});};
window.addEventListener('pagehide',()=>{clearTimeout(previewTimer);if(previewUrl)URL.revokeObjectURL(previewUrl);});
(async()=>{({profile}=await bootShell());const {data:me,error:m}=await supabase.from('employees').select('department_id,center_id,signature_url').eq('id',profile.id).single();if(m)throw m;signaturePath=me.signature_url;const {data,error}=await supabase.from('employees').select('id,full_name,department_id,center_id,departments(code),system_roles(code)').eq('status','active').order('full_name');if(error)throw error;people=data||[];const options=list=>'<option value="">Chọn người ký</option>'+list.filter(p=>p.id!==profile.id).map(p=>`<option value="${p.id}">${esc(p.full_name)}</option>`).join('');$('managerSigner').innerHTML=options(people.filter(p=>p.department_id&&p.department_id===me.department_id&&['DEPT_HEAD','DEPT_DEPUTY'].includes(p.system_roles?.code)||p.center_id&&p.center_id===me.center_id&&p.system_roles?.code==='CENTER_MANAGER'));$('hrSigner').innerHTML=options(people.filter(p=>p.departments?.code==='HR'&&['DEPT_HEAD','DEPT_DEPUTY'].includes(p.system_roles?.code)));$('directorSigner').innerHTML=options(people.filter(p=>p.system_roles?.code==='EXECUTIVE'));$('documentType').innerHTML=DOCUMENT_TEMPLATES.filter(t=>!t.group||t.group===(profile.isTeacher?'teacher':'office')).map(t=>`<option value="${t.code}">${esc(t.title)}</option>`).join('');await load();})().catch(err);
