const field=(key,label,type='text',required=true)=>({key,label,type,required});
const leaveFields=[field('start_date','Ngày bắt đầu','date'),field('days','Số ngày','number'),field('return_date','Ngày đi làm lại','date',false),field('reason_note','Lý do','textarea'),field('handover','Công việc / lớp dạy bàn giao','textarea',false),field('replacement','Người nhận bàn giao','text',false)];
export const DOCUMENT_TEMPLATES=[
 ...[
 ['06.Donxinhoandoingaynghi','Hoán đổi ngày nghỉ hàng tuần','office'],['07.Donxinnghiphepcanbo','Nghỉ phép cán bộ','office'],['08.Donxinnghibu','Nghỉ bù cán bộ','office'],['09.Donxinnghikhongluongcanbo','Nghỉ không lương cán bộ','office'],['10.Donxinhoandoilichdaydaybu','Hoán đổi lịch dạy / dạy bù','teacher'],['11.Donxinnghiphep','Nghỉ phép giáo viên','teacher'],['12.Donxinnghibu','Nghỉ bù giáo viên','teacher'],['13.Donxinnghikhongluonggiaovien','Nghỉ không lương giáo viên','teacher']
 ].map(([code,title,group])=>({code,title,group,source:'leave_requests',fields:[...leaveFields,...(code.startsWith('06')?[field('swap_date','Ngày nghỉ hoán đổi','date')]:code.startsWith('10')?[field('original_schedule','Lịch dạy chính thức'),field('makeup_schedule','Lịch dạy bù')]:[])]})),
 {code:'business_trip',title:'Đơn công tác',source:'business_trips',fields:[field('title','Nội dung công tác'),field('trip_date','Ngày công tác','date'),field('days','Số ngày','number'),field('origin_address','Điểm đi'),field('destination_address','Điểm đến'),field('distance_km','Khoảng cách (km)','number',false),field('content','Mục đích / kế hoạch','textarea')]},
 {code:'administrative_request',title:'Đơn hành chính khác',source:null,fields:[field('title','Tiêu đề đơn'),field('content','Nội dung đề nghị','textarea'),field('effective_date','Ngày áp dụng','date',false)]}
];
export function validateDocument(template,data){for(const f of template.fields){const v=data[f.key];if(f.required&&!String(v??'').trim())throw new Error(`Vui lòng nhập ${f.label.toLowerCase()}.`);if(f.type==='number'&&v!==''&&v!==undefined&&(!Number.isFinite(Number(v))||Number(v)<0))throw new Error(`${f.label} không hợp lệ.`);}if('days'in data&&(![.5,1,1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10].includes(Number(data.days))&&(Number(data.days)<=0||Number(data.days)>366||Number(data.days)*2%1!==0)))throw new Error('Số ngày phải dương, bước 0,5 và không quá 366.');if(data.return_date&&data.start_date&&data.return_date<data.start_date)throw new Error('Ngày đi làm lại phải sau ngày bắt đầu.');return data;}
